Repository Toughie17/MACC_TEAM4_HODORI, pull requests merged in 2023-10, with the labels that each got.

#13 [feat] 회의 뷰 개발
  Hodori.xcodeproj/project.pbxproj
  Hodori/ContentView.swift
  Hodori/Extensions/Color+.swift
  Hodori/Extensions/Font+.swift
  Hodori/Extensions/Int+.swift
  Hodori/Extensions/String+.swift
  Hodori/Info.plist
  Hodori/Managers/MeetingManager.swift
  Hodori/Managers/TimerManager.swift
  Hodori/Resources/Assets.xcassets/cancelButton.imageset/Contents.json
  Hodori/Resources/Assets.xcassets/cancelButton.imageset/Frame 1163.png
  Hodori/Resources/Assets.xcassets/darkgray.colorset/Contents.json
  Hodori/Resources/Assets.xcassets/pauseButton.imageset/Contents.json
  Hodori/Resources/Assets.xcassets/pauseButton.imageset/Frame 1217.png
  Hodori/Resources/Assets.xcassets/playButton.imageset/Contents.json
  Hodori/Resources/Assets.xcassets/playButton.imageset/Frame 1164.png
  Hodori/Resources/Pretendard/Pretendard-Medium.otf
  Hodori/Resources/Pretendard/Pretendard-Regular.otf
  Hodori/Resources/Pretendard/Pretendard-SemiBold.otf
  Hodori/Views/AfterMeetingView.swift
  Hodori/Views/ExtendMeetingView.swift
  Hodori/Views/MeetingEndCheckView.swift
  Hodori/Views/MeetingView/MeetingView.swift
  Hodori/Views/MeetingView/ProgressBarCell.swift
  Hodori/Views/MeetingView/TimerCell.swift
  Hodori/Views/NewMeetingSetupView/ConfirmationAlert.swift
  Hodori/Views/NewMeetingSetupView/NewMeetingSetupView.swift
  Hodori/Views/NewMeetingSetupView/TimePickerView.swift
  Hodori/Views/TimerComponent.swift
Labels: 🐳 에릭, development

#14 [feat] MeetingEndCheckView & ExtendMeetingView
  Hodori.xcodeproj/project.pbxproj
  Hodori/ContentView.swift
  Hodori/Extensions/Color+.swift
  Hodori/Extensions/Int+.swift
  Hodori/Managers/MeetingManager.swift
  Hodori/Views/AfterMeetingView.swift
  Hodori/Views/ExtendMeetingView.swift
  Hodori/Views/MeetingEndCheck/ExtendMeetingView.swift
  Hodori/Views/MeetingEndCheck/MeetingEndCheckView.swift
  Hodori/Views/MeetingEndCheck/TimerTestDummy.swift
  Hodori/Views/MeetingEndCheckView.swift
Labels: 🐱 터피, development

#16 [feat] 사운드 재생 구현
  Hodori.xcodeproj/project.pbxproj
  Hodori/Managers/SoundManager.swift
  Hodori/Managers/TimerManager.swift
  Hodori/Resources/leftMinutesSound.mp3
  Hodori/Resources/timerEndSound.mp3
  Hodori/Views/MeetingEndCheck/ExtendMeetingView.swift
  Hodori/Views/MeetingEndCheck/MeetingEndCheckView.swift
  Hodori/Views/MeetingEndCheck/TimerTestDummy.swift
  Hodori/Views/MeetingView/MeetingView.swift
  Hodori/Views/NewMeetingSetupView/NewMeetingSetupView.swift
Labels: 🐱 터피, development

#18 [feat] 타이머 정지 버튼 기능 추가 및 버그 수정
  Hodori.xcodeproj/project.pbxproj
  Hodori/Managers/MeetingManager.swift
  Hodori/Managers/TimerManager.swift
  Hodori/Views/MeetingEndCheck/ExtendMeetingView.swift
  Hodori/Views/MeetingView/MeetingView.swift
  Hodori/Views/MeetingView/ProgressBarCell.swift
  Hodori/Views/MeetingView/TimerCell.swift
  Hodori/Views/NewMeetingSetupView/ConfirmationAlert.swift
  Hodori/Views/NewMeetingSetupView/NewMeetingSetupView.swift
Labels: bug, 🐳 에릭, development

#19 [feat] MeetingAfterView 개발
  Hodori.xcodeproj/project.pbxproj
  Hodori/Extensions/Color+.swift
  Hodori/Views/MeetingAfterView.swift
  Hodori/Views/MeetingEndCheck/MeetingEndCheckView.swift
Labels: 🥭 망고, development
